// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://unytklkgzjfxctnuugjf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVueXRrbGtnempmeGN0bnV1Z2pmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU3Mjg0OTgsImV4cCI6MjA2MTMwNDQ5OH0.21CImcoguTT3PH6pQnF2zBzkAG88GBLPQJnYNkhb69M";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);